### PR TITLE
removed c++ include directive for syntax highlighting

### PR DESCRIPTION
**Pull request by kylefleming**
As per #65

### CODE REVIEW

**Comment by b-g** [comment]
Many Thanks! However, did you see this old discussion? https://github.com/b-g/processing-sublime/issues/20
Can you confirm that it doesn't brake other things? (maybe provide a few screenshots for discussion)

**Comment by b-g** [comment]
Many Thanks! However, did you see this old discussion? https://github.com/b-g/processing-sublime/issues/20
Can you confirm that it doesn't brake other things? (maybe provide a few screenshots for discussion)

**Comment by kylefleming** [comment]
I've been using the version in this pull request for the past 3 or 4 months. I'm pretty certain nothing is broken and several of the styling issues have been fixed, including where it adds a red line to the end of classes (red line indicating an error in parsing the syntax).

**Comment by b-g** [comment]
I gave it a try, rejected ... it brakes everything (first one w/o c++ include), note all the processing functions like pushMatrix()!

screen shot 2015-06-05 at 17 30 15
screen shot 2015-06-05 at 17 37 20

Any ideas to solve this issue?

**Pull request merged**
