### PR TITLE
Updated readme with close old sketch on build trick

### PR DESCRIPTION
**Pull request by akaleeroy**
Added instructions to modify your build system on Windows to close the old sketch on build.

### CODE REVIEW

**Comment by b-g** [comment]
Hi @akaleeroy, many thanks for this!! However please split the pull request into smaller chunks:

1. new buildsystems. (Did you test them on linux, osx and windows? And I actually don't get why we should then modify the readme if the new new buildsystems become included as default?)

2. all your new snippets

And last please exclude Syntaxes/Processing.tmLanguage as this is an ongoing unsolved discussion (see open issues)

Thanks again!
Benedikt

**Comment by akaleeroy** [comment]
Sure, I'll try, but this was my first time, I didn't know that the second commit would show up here, sorry.

**Comment by b-g** [comment]
Thanks! No worries! I really appreciate your help and contribution! :)

**Comment by akaleeroy** [comment]
About the new build systems - I tried it on Ubuntu, and it fails. It should work because it works from the terminal. But not from within the Sublime build system. 

    Running pkill -f "java.*Esfera"; ~/Processing/processing-java --sketch="/home/leeroy/Processing/modes/java/examples/Demos/Performance/Esfera" --output="/home/leeroy/Processing/modes/java/examples/Demos/Performance/Esfera/build-test" --run --force
    Traceback (most recent call last):
      File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 294, in finish
      File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 244, in append_string
      File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 92, in kill
      File "./subprocess.py", line 1762, in terminate
      File "./subprocess.py", line 1757, in send_signal
    ProcessLookupError: [Errno 3] No such process

Haven't tried on OSX. I understand `pkill` is available on Mac OS X 10.8 and later so it matches the Processing supported platforms.

Assuming this is resolved in the end, should this behavior be the default, or a variant? It does slow down the build a tiny bit - .4s on my Windows 7 machine.

**Comment by b-g** [comment]
Thanks for the investigation! I would say variant for now ... if then people start to use the feature and we have good feedback we make it the default one. Good luck!

**Pull request closed without merging**
