### PR TITLE
Pure java plugin

### PR DESCRIPTION
**Pull request by ybakos**
I have incorporated some additional changes per feedback on [this rejected pull request](https://github.com/b-g/processing-sublime/pull/72), including:

- Prerequisites section for installing ant, etc.
- Example of project package name.

Note that I did not provide instructions to install ant. My reasoning is that, if a person does not know how to install ant, they shouldn't (nor would they want to) be using this command any way.

@b-g My main concern is that you did not see the generated .java files after running the command. Please try this pull request when you can, and let me know what happens. In the mean time, I will also try this on a "clean" installation of Sublime to see if I can replicate that issue.

Thanks for your help and feedback!

### CODE REVIEW

**Comment by b-g** [comment]
Hi @ybakos,

Gave it another try ... still not working. But I think it might be us just a broken file path issue. ST console says:

```
Traceback (most recent call last):
  File "/Users/bene/Library/Application Support/Sublime Text 3/Packages/processing-sublime/Processing.py", line 29, in generate_project
    package_name)
  File "/Users/bene/Library/Application Support/Sublime Text 3/Packages/processing-sublime/Processing.py", line 38, in generate_files_from_template
    self.generate_buildfile(template_path, package_name)
  File "/Users/bene/Library/Application Support/Sublime Text 3/Packages/processing-sublime/Processing.py", line 42, in generate_buildfile
    with open(os.path.join(template_path, BUILDFILE_TEMPLATE_NAME), 'r') as build_template:
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Sublime Text.app/Contents/MacOS/Commands/templates/new_java_ant_project/build.xml.template'
```

Documentation is now great! I just would change the headline:
- It should be a ## hierarchy one IMO, on the same level like Usage and Hints
- I would make it a bit more teaser like "New Java Ant Project Command (pure Java Processing project)" or "New Java Ant Project Command – Bye bye Eclipse monster" :)

Thanks!

**Comment by ybakos** [comment]
Thanks for the feedback. Ok,, I will spend some time debugging that with ST3.

I chose to put the command instructions under "Usage" since it's part of using the package. What do you think?

I'll update the header title to be more fun. :)

**Comment by b-g** [comment]
👍

I think under "Usage" makes sense form the logic point of view ... but as I think this is a really a super nice feature! I would vote for making in more prominent. 

One thing which crossed my mind is that a lot of people only have to use Eclipse for creating processing libraries. Would it not be cool to have a "New Processing Library" command?! Just brainstorming 😀

**Comment by ybakos** [comment]
@b-g Yeah, I think that a library command would be helpful too. Add a new issue and we can use it to track the development of that feature.

**Comment by ybakos** [comment]
@b-g I'll need to work on this some more to ensure compatibility with ST3. (Did you try it with ST2? I'd also like to verify that it at least works with ST2, which it does for me.)

**Comment by b-g** [comment]
@ybakos

1. I can confirm that it works with ST2
2. Added new issue to track development of the library command

screen shot 2015-06-20 at 11 09 34

**Pull request closed without merging**
